language: go

go:
  - '1.11'
  - tip

git:
  depth: 3

os:
  - osx
  - linux

env:
  global:
    - GO111MODULE=on
    - GOPATH="${TRAVIS_HOME}/gopath"
    - GOBIN="${GOPATH}/bin"
    - GOLINT="${GOBIN}/golint"
    - PATH="${GOBIN}:${PATH}"
  matrix:
    - CLIP_PROGRAM="xclip"
    - CLIP_PROGRAM="xsel"

cache:
  directories:
    ## Preserve golint executable.
    - $GOLINT_BIN
    ## Preserve Go module cache.
    - $GOPATH/pkg/mod/cache

## Mark Go version 'tip' as an optional.
matrix:
  exclude:
    - os: osx
      env: CLIP_PROGRAM="xsel"
  allow_failures:
    - go: 'tip'
  fast_finish: true

## Install dependencies and code review tools.
before_install:
  - echo "GOBIN=${GOBIN}" "GOLINT_BIN=${GOLINT_BIN}" "PATH=${PATH}"

  ## Install golint, if no installation cache exists.
  - |
    if ! command -v golint > /dev/null; then
      rm -rf $GOLINT_BIN
      echo "Installing 'golint'..."
      GO111MODULE=off go get -u golang.org/x/lint/golint
    fi
  - command -v golint

  ## Install clipboard program if necessary.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install "$CLIP_PROGRAM";
    fi

## Install all dependencies, start dependency services.
install:
  - make dl
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start # imitate an display on Linux
    fi

## List diagonstic information before running tests.
before_script:
  - go env

## Check code, perform tests with race-condition-checking.
script: make review-race-v

after_success:
  - bash <(curl -s https://codecov.io/bash)
