language: go

go:
  - '1.10'
  - '1.11'
  - tip

git:
  depth: 3

os:
  - osx
  - linux

env:
  global:
    - GOLINT_BIN="$GOPATH/bin/golint"
  matrix:
    - CLIP_PROGRAM="xclip"
    - CLIP_PROGRAM="xsel"

## Cache Golint installation.
cache:
  directories:
    - $GOLINT_BIN

## Mark Go version 'tip' as an optional.
matrix:
  exclude:
    - os: osx
      env: CLIP_PROGRAM="xsel"
  allow_failures:
    - go: 'tip'
  fast_finish: true

## Install dependencies and code review tools.
before_install:
  ## Install Golint, if no installation cache exists.
  - if [ ! -e "$GOLINT_BIN" ]; then go get -u golang.org/x/lint/golint; fi

  ## Install clipboard program if necessary.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo apt-get install "$CLIP_PROGRAM";
    fi

install:
  ## Install all sub-packages; include tests.
  - go get -t ./...

## List diagonstic information before running tests.
before_script:
  - go env

script: |
  if [ "$TRAVIS_OS_NAME" == "osx" ];
  then make review-race-v;
  else xvfb-run make review-race-v; # imitate an display on Linux
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
